# Generated by Django 4.0.3 on 2022-04-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chategory_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
