# Generated by Django 4.0.3 on 2022-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
