# Generated by Django 4.0.4 on 2022-04-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('detail', models.CharField(max_length=100)),
                ('duedate', models.DateTimeField(null=True)),
                ('left_day', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
